repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0  # Use the version of black you want; 'stable' for the latest stable release
    hooks:
      - id: black
        language_version: python3.11.6  # Optional: specify the Python version
